LinksAndTags/Controllers/Web/AppController.cs
using Microsoft.AspNetCore.Mvc;
using LinksAndTags.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using LinksAndTags.Services;
using Microsoft.Extensions.Configuration;
using LinksAndTags.Models;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authorization;

namespace LinksAndTags.Controllers.Web
{
    public class AppController : Controller
    {
        private IMailService _mailService;
        private IConfigurationRoot _config;

        public AppController(IMailService mailService, 
            IConfigurationRoot config, 
            LinksAndTagsContext context, 
            ILinksAndTagsRepository repository,
            ILogger<AppController> logger)
        {
            _mailService = mailService;
            _config = config;
        }

        public IActionResult Index()
        {
            return View();                       
        }

        [Authorize]
        public IActionResult Links()
        {
            return View();
        }

        public IActionResult About()
        {           
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Contact(ContactViewModel model)
        {
            _mailService.SendMail(_config["MailSettings:ToAddress"], model.Email, "From Links", model.Message);
            ModelState.Clear();
            ViewBag.UserMessage = "Message Sent";
            return View();
        }
    }
}

LinksAndTags/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    

    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/bootswatch/yeti/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>
    <div id="sidebar">       
        <ul class="nav">
            @if (User.Identity.IsAuthenticated)
            {
            <li id="username">Welcome @User.Identity.Name!</li>
            }  
            <li class="active"><a asp-controller="App" asp-action="Index">Home</a></li>
            <li><a asp-controller="App" asp-action="About">About</a></li>
            <li><a asp-controller="App" asp-action="Contact">Contact</a></li>
            @if (User.Identity.IsAuthenticated)
            {
                <li><a asp-controller="App" asp-action="Links">My links</a></li>
                <li><a asp-controller="Auth" asp-action="Logout">Logout</a></li>
            }
            else
            {
                <li><a asp-controller="Auth" asp-action="Register">Register</a></li>
            }           
        </ul>
    </div>
    <div id="wrapper">
        <nav>
            <div class="container-fluid" id="sidebarToggleDiv">
                <button id="sidebarToggle" class="btn btn-primary">
                    <i class="fa fa-angle-left"></i>
                </button>
            </div>
        </nav>
        <div id="main" class="container-fluid">
            <div>
                @RenderBody()
            </div>          
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/site.js"></script>
    @RenderSection("scripts",false)
</body>
</html>